controllers:
    resource: ../src/Controller/
    type: attribute

# redirecting the homepage
homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\AccueilController.php::urlRedirectAction
    defaults:
        path: /
        permanent: true